stages:
  - build
  - test
  - package

variables:
  GIT_DEPTH: 1

before_script:
  - apt-get update -qq && apt-get install -y -qq build-essential dpkg-dev

build_job:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - maxfinder
    expire_in: 1 hour

test_job:
  stage: test
  script:
    - make test
  dependencies:
    - build_job

package_job:
  stage: package
  script:
    - make package
  artifacts:
    paths:
      - "*.deb"
    expire_in: 1 week
  dependencies:
    - build_job
  only:
    - main
    - master
